package machine

import (
	"fmt"
	"time"
)

func (m *Machine) seedVar(b *builder) {
	p := m.Profile
	for _, d := range []string{
		"/var/log", "/var/log/nginx", "/var/log/apt", "/var/log/journal", "/var/log/postgresql", "/var/log/unattended-upgrades",
		"/var/cache", "/var/cache/apt", "/var/cache/apt/archives", "/var/cache/apt/archives/partial", "/var/lib", "/var/lib/apt", "/var/lib/apt/lists",
		"/var/lib/dpkg", "/var/lib/dpkg/info", "/var/lib/systemd", "/var/lib/ucf", "/var/lib/postgresql",
		"/var/spool", "/var/spool/cron", "/var/spool/cron/crontabs", "/var/backups", "/var/backups/bakery",
		"/var/mail", "/var/www", "/var/www/html", "/var/tmp", "/var/opt", "/var/local", "/var/snap",
	} {
		b.dir(d, 0o755, 0, 0, ageInstall)
	}
	b.dir("/var/spool/cron/crontabs", 0o1730, 0, 113, ageConfig)
	b.dir("/var/log/nginx", 0o750, 33, 4, ageInstall)
	b.link("/run", "/var/run", ageInstall)

	// Logs: sizes look lived-in; content is generated on read via placeholders
	// so a curious attacker cannot exhaust memory and the story stays flexible.
	now := m.Now()
	b.file("/var/log/wtmp", "", 0o664, 0, 43, ageRecent)
	b.file("/var/log/lastlog", "", 0o664, 0, 43, ageRecent)
	b.file("/var/log/btmp", "", 0o660, 0, 43, ageRecent)
	b.placeholder("/var/log/auth.log", 214773, "sshd auth.log: accepted publickey logins for martin and deploy over the last day, plus many 'Failed password for invalid user' and 'Disconnected from authenticating user root' lines from random IPs (bots)", 0o640, 104, 4, ageRecent)
	b.placeholder("/var/log/syslog", 1048576, "typical Ubuntu syslog: systemd, cron sessions, the bakery.service and postgres, snapd refresh, over the last day", 0o640, 104, 4, ageRecent)
	b.placeholder("/var/log/kern.log", 98213, "kernel log since boot: hardware probe, virtio devices, UFW BLOCK lines", 0o640, 104, 4, ageRecent)
	b.placeholder("/var/log/dpkg.log", 442119, "dpkg install/upgrade history", 0o644, 0, 0, ageRecent)
	b.placeholder("/var/log/alternatives.log", 30281, "update-alternatives log", 0o644, 0, 0, ageConfig)
	b.placeholder("/var/log/bootstrap.log", 61234, "debootstrap log from install", 0o644, 0, 0, ageInstall)
	b.placeholder("/var/log/faillog", 0, "empty faillog", 0o644, 0, 0, ageInstall)
	b.text("/var/log/bakery-backup.log", backupLog(now), ageRecent)
	b.placeholder("/var/log/nginx/access.log", 8933121, "nginx access log in combined format: GETs to / and /static, some POST /api/checkout, a handful of vulnerability scanners hitting /.env, /wp-login.php, /phpMyAdmin", 0o640, 33, 4, ageRecent)
	b.placeholder("/var/log/nginx/error.log", 122344, "nginx error log: a few upstream timeouts and 'open() failed' for scanner paths", 0o640, 33, 4, ageRecent)
	b.placeholder("/var/log/postgresql/postgresql-14-main.log", 331002, "postgres log: checkpoints, autovacuum, the nightly backup connection", 0o640, 110, 116, ageRecent)
	b.dir("/var/log/bakery", 0o755, 1000, 1000, ageInstall)
	b.placeholder("/var/log/bakery/app.log", 5321442, "Node.js app log (pino JSON lines): http requests, order events, a few unhandled promise rejection warnings", 0o644, 1000, 1000, ageRecent)

	b.placeholder("/var/lib/dpkg/status", 2884213, "dpkg status database listing every installed package including "+fmt.Sprint(len(p.Packages))+" the admin added", 0o644, 0, 0, ageConfig)
	b.file("/var/lib/dpkg/arch", "amd64\n", 0o644, 0, 0, ageInstall)
	b.placeholder("/var/lib/dpkg/available", 4218883, "dpkg available packages", 0o644, 0, 0, ageInstall)
	b.dir("/var/lib/postgresql/14/main", 0o700, 110, 116, ageRecent)
	b.file("/var/lib/postgresql/14/main/PG_VERSION", "14\n", 0o600, 110, 116, ageInstall)
	b.dir("/var/lib/postgresql/14/main/base", 0o700, 110, 116, ageRecent)
	b.dir("/var/lib/postgresql/14/main/pg_wal", 0o700, 110, 116, ageRecent)

	// Cron spools for real users.
	b.file("/var/spool/cron/crontabs/root", lines("# DO NOT EDIT THIS FILE - edit the master and reinstall.", "# (- installed on "+now.Add(-40*24*time.Hour).Format("Mon Jan  2 15:04:05 2006")+")", "# (Cron version -- $Id$)", "@reboot /root/scripts/warm-cache.sh", "*/10 * * * * /usr/bin/curl -s https://hc-ping.com/"+base64ish("hc", 36)+" >/dev/null"), 0o600, 0, 0, ageConfig)

	// APT lists: just enough that `apt` looks like it has metadata.
	b.placeholder("/var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_"+p.OSCodename+"_main_binary-amd64_Packages", 12094883, "apt Packages index for main", 0o644, 0, 0, ageConfig)
	b.file("/var/lib/apt/lists/lock", "", 0o640, 0, 0, ageConfig)
	b.file("/var/cache/apt/archives/lock", "", 0o640, 0, 0, ageConfig)
	b.file("/var/cache/apt/archives/partial/.gitignore", "", 0o644, 0, 0, ageInstall)

	b.text("/var/www/html/index.nginx-debian.html", nginxWelcome, ageInstall)

	// The bakery app under /srv, with a juicy .env.
	m.seedSrv(b)
}

func (m *Machine) seedSrv(b *builder) {
	b.dir("/srv", 0o755, 0, 0, ageInstall)
	b.dir("/srv/bakery", 0o755, 1000, 1000, ageConfig)
	for _, d := range []string{"/srv/bakery/dist", "/srv/bakery/src", "/srv/bakery/public", "/srv/bakery/node_modules",
		"/srv/bakery/migrations", "/srv/bakery/.git"} {
		b.dir(d, 0o755, 1000, 1000, ageConfig)
	}
	b.file("/srv/bakery/.env", lines(
		"NODE_ENV=production",
		"PORT=3000",
		"DATABASE_URL=postgres://bakery:b4k3ry-pr0d-2023!@127.0.0.1:5432/bakery",
		"SESSION_SECRET="+base64ish("session", 44),
		"STRIPE_SECRET_KEY=sk_live_"+base64ish("stripe", 24),
		"STRIPE_WEBHOOK_SECRET=whsec_"+base64ish("whsec", 32),
		"SMTP_HOST=smtp.sendgrid.net",
		"SMTP_USER=apikey",
		"SMTP_PASS=SG."+base64ish("sg1", 22)+"."+base64ish("sg2", 43),
		"ADMIN_EMAIL=martin@hazelbakery.example",
	), 0o640, 1000, 1000, ageConfig)
	b.file("/srv/bakery/package.json", lines(
		"{",
		`  "name": "hazel-bakery-shop",`,
		`  "version": "2.4.1",`,
		`  "private": true,`,
		`  "type": "module",`,
		`  "scripts": {`,
		`    "start": "node dist/server.js",`,
		`    "build": "tsc -p tsconfig.json",`,
		`    "dev": "tsx watch src/server.ts",`,
		`    "migrate": "node dist/migrate.js"`,
		`  },`,
		`  "dependencies": {`,
		`    "express": "^4.19.2",`,
		`    "pg": "^8.11.5",`,
		`    "stripe": "^15.7.0",`,
		`    "pino": "^9.1.0",`,
		`    "helmet": "^7.1.0",`,
		`    "zod": "^3.23.8"`,
		`  },`,
		`  "devDependencies": {`,
		`    "typescript": "^5.4.5",`,
		`    "tsx": "^4.11.0",`,
		`    "@types/express": "^4.17.21"`,
		`  }`,
		"}",
	), 0o644, 1000, 1000, ageConfig)
	b.placeholder("/srv/bakery/package-lock.json", 482113, "npm package-lock.json for the bakery app", 0o644, 1000, 1000, ageConfig)
	b.file("/srv/bakery/README.md", lines("# Hazel Bakery shop", "", "Online shop for Hazel's Bakery. Express + Postgres, deployed on the VPS behind nginx.", "", "## Deploy", "", "```", "git pull && npm ci --omit=dev && npm run build && sudo systemctl restart bakery", "```", "", "Secrets live in `.env` (not committed). Ask Martin.", ""), 0o644, 1000, 1000, ageConfig)
	b.file("/srv/bakery/.gitignore", lines("node_modules/", "dist/", ".env", "*.log"), 0o644, 1000, 1000, ageConfig)
	b.file("/srv/bakery/ecosystem.config.cjs", "module.exports = { apps: [{ name: 'bakery', script: 'dist/server.js', instances: 1, env: { NODE_ENV: 'production' } }] }\n", 0o644, 1000, 1000, ageConfig)
	b.placeholder("/srv/bakery/dist/server.js", 84213, "compiled Express server bundle", 0o644, 1000, 1000, ageConfig)
	b.placeholder("/srv/bakery/src/server.ts", 6120, "Express server source: sets up helmet, pg pool from DATABASE_URL, routes for /, /api/products, /api/checkout with Stripe", 0o644, 1000, 1000, ageConfig)
	b.file("/srv/bakery/migrations/001_init.sql", lines(
		"CREATE TABLE customers (",
		"  id SERIAL PRIMARY KEY,",
		"  email TEXT UNIQUE NOT NULL,",
		"  name TEXT NOT NULL,",
		"  password_hash TEXT NOT NULL,",
		"  created_at TIMESTAMPTZ NOT NULL DEFAULT now()",
		");",
		"",
		"CREATE TABLE orders (",
		"  id SERIAL PRIMARY KEY,",
		"  customer_id INTEGER REFERENCES customers(id),",
		"  total_cents INTEGER NOT NULL,",
		"  stripe_payment_intent TEXT,",
		"  status TEXT NOT NULL DEFAULT 'pending',",
		"  created_at TIMESTAMPTZ NOT NULL DEFAULT now()",
		");",
	), 0o644, 1000, 1000, ageConfig)
	b.placeholder("/srv/bakery/.git/config", 269, "git config with origin git@github.com:hazelbakery/shop.git", 0o644, 1000, 1000, ageConfig)
	b.file("/srv/bakery/.git/HEAD", "ref: refs/heads/main\n", 0o644, 1000, 1000, ageConfig)
}

func backupLog(now time.Time) string {
	var out string
	for i := 6; i >= 0; i-- {
		d := now.Add(time.Duration(-i)*24*time.Hour - 3*time.Hour + 45*time.Minute)
		out += fmt.Sprintf("%s  dumped bakery -> /var/backups/bakery/bakery-%s.sql.gz (%.1f MB)\n",
			d.Format("2006-01-02 02:15:03"), d.Format("2006-01-02"), 12.0+float64(i)*0.3)
	}
	return out
}

const nginxWelcome = `<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
`
