package machine

import (
	"io/fs"
	"path"

	"github.com/amirradjou/llm-honeypot/internal/profile"
)

func (m *Machine) seedHomes(b *builder) {
	p := m.Profile
	for _, u := range p.Users {
		if u.UID != 0 && (u.UID < 1000 || u.UID == 65534) && u.Name != "postgres" {
			continue
		}
		home := u.Home
		if u.Name == "postgres" {
			home = "/var/lib/postgresql"
		}
		b.dir(home, homeMode(u.Name), u.UID, u.GID, ageHome)
		b.file(under(home, ".bashrc"), bashrc, 0o644, u.UID, u.GID, ageInstall)
		b.file(under(home, ".profile"), profileRc, 0o644, u.UID, u.GID, ageInstall)
		if u.Name != "postgres" {
			b.file(under(home, ".bash_logout"), bashLogout, 0o644, u.UID, u.GID, ageInstall)
		}
		b.dir(under(home, ".ssh"), 0o700, u.UID, u.GID, ageHome)
		b.dir(under(home, ".cache"), 0o700, u.UID, u.GID, ageHome)
		b.file(under(home, ".cache/motd.legal-displayed"), "", 0o644, u.UID, u.GID, ageHome)
		switch u.Name {
		case "root":
			m.seedRoot(b, home)
		case "deploy":
			b.file(under(home, ".bash_history"), deployHistory, 0o600, u.UID, u.GID, ageHome)
			b.file(under(home, ".ssh/authorized_keys"), "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI"+base64ish("deploy-key", 43)+" deploy@ci-runner\n", 0o600, u.UID, u.GID, ageConfig)
			b.dir(under(home, ".npm"), 0o755, u.UID, u.GID, ageHome)
			b.dir(under(home, ".pm2"), 0o755, u.UID, u.GID, ageHome)
			b.placeholder(under(home, ".npmrc"), 61, "npmrc with registry and a fund=false line", 0o600, u.UID, u.GID, ageConfig)
		case "martin":
			b.file(under(home, ".bash_history"), martinHistory, 0o600, u.UID, u.GID, ageHome)
			b.file(under(home, ".ssh/authorized_keys"), "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI"+base64ish("martin-key", 43)+" martin@thinkpad\n", 0o600, u.UID, u.GID, ageConfig)
			b.file(under(home, ".ssh/known_hosts"), knownHosts(p), 0o644, u.UID, u.GID, ageHome)
			b.file(under(home, ".gitconfig"), "[user]\n\tname = Martin Kowalski\n\temail = martin@hazelbakery.example\n[pull]\n\trebase = false\n", 0o644, u.UID, u.GID, ageConfig)
			b.file(under(home, ".sudo_as_admin_successful"), "", 0o644, u.UID, u.GID, ageHome)
			b.placeholder(under(home, ".viminfo"), 8123, "vim .viminfo with recent files /etc/nginx/sites-available/bakery and /srv/bakery/.env", 0o600, u.UID, u.GID, ageHome)
			b.placeholder(under(home, ".lesshst"), 43, "less history file", 0o600, u.UID, u.GID, ageHome)
			b.placeholder(under(home, ".wget-hsts"), 173, "wget HSTS database with one entry for deb.nodesource.com", 0o644, u.UID, u.GID, ageHome)
			b.dir(under(home, "notes"), 0o755, u.UID, u.GID, ageHome)
			b.file(under(home, "notes/todo.txt"), lines(
				"- rotate the bakery db password (still the one from the migration!)",
				"- move backups off-box, /var/backups fills up",
				"- ask Hazel about the black friday traffic estimate",
				"- upgrade node 18 -> 20 on staging first",
			), 0o644, u.UID, u.GID, ageHome)
		case "postgres":
			b.dir(under(home, "14"), 0o755, u.UID, u.GID, ageInstall)
			b.dir(under(home, "14/main"), 0o700, u.UID, u.GID, ageInstall)
			b.file(under(home, ".psql_history"), lines("\\l", "\\c bakery", "select count(*) from orders;", "select email from customers order by created_at desc limit 20;", "\\q"), 0o600, u.UID, u.GID, ageHome)
			b.file(under(home, ".bash_history"), lines("psql", "pg_lsclusters", "psql -c 'select version()'", "exit"), 0o600, u.UID, u.GID, ageHome)
		}
	}
}

func homeMode(user string) fs.FileMode {
	if user == "root" {
		return 0o700
	}
	return 0o750
}

func (m *Machine) seedRoot(b *builder, home string) {
	b.file(under(home, ".bash_history"), rootHistory, 0o600, 0, 0, ageHome)
	b.file(under(home, ".ssh/authorized_keys"), "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI"+base64ish("root-key", 43)+" martin@thinkpad\n", 0o600, 0, 0, ageConfig)
	b.file(under(home, ".ssh/known_hosts"), knownHosts(m.Profile), 0o644, 0, 0, ageHome)
	b.placeholder(under(home, ".viminfo"), 12904, "vim .viminfo listing /etc/nginx/nginx.conf, /etc/fail2ban/jail.local, /root/scripts/backup.sh", 0o600, 0, 0, ageHome)
	b.placeholder(under(home, ".lesshst"), 61, "less history file", 0o600, 0, 0, ageHome)
	b.file(under(home, ".selected_editor"), "# Generated by /usr/bin/select-editor\nSELECTED_EDITOR=\"/usr/bin/vim.basic\"\n", 0o644, 0, 0, ageInstall)
	b.file(under(home, ".wget-hsts"), lines("# HSTS 1.0 Known Hosts database for GNU Wget.", "# Edit at your own risk.", "# <hostname>\t<port>\t<incl. subdomains>\t<created>\t<max-age>", "deb.nodesource.com\t0\t1\t1719412244\t31536000", "github.com\t0\t1\t1717001873\t31536000"), 0o644, 0, 0, ageHome)
	b.dir(under(home, "scripts"), 0o700, 0, 0, ageConfig)
	b.file(under(home, "scripts/backup.sh"), lines(
		"#!/bin/bash",
		"# nightly dump of the shop database, keep 7 days",
		"set -euo pipefail",
		"",
		"export PGPASSWORD='b4k3ry-pr0d-2023!'",
		"DEST=/var/backups/bakery",
		"mkdir -p \"$DEST\"",
		"pg_dump -h 127.0.0.1 -U bakery bakery | gzip > \"$DEST/bakery-$(date +%F).sql.gz\"",
		"find \"$DEST\" -name 'bakery-*.sql.gz' -mtime +7 -delete",
		"",
		"# TODO: sync to the hetzner storage box (see notes)",
		"# rclone copy \"$DEST\" storagebox:bakery-backups/",
	), 0o700, 0, 0, ageConfig)
	b.file(under(home, "scripts/renew-hook.sh"), lines("#!/bin/sh", "systemctl reload nginx"), 0o700, 0, 0, ageConfig)
	b.dir(under(home, ".config"), 0o700, 0, 0, ageHome)
	b.dir(under(home, ".local"), 0o700, 0, 0, ageHome)
	b.dir(under(home, ".local/share"), 0o700, 0, 0, ageHome)
	b.dir(under(home, ".local/share/nano"), 0o700, 0, 0, ageHome)
	b.dir(under(home, "snap"), 0o700, 0, 0, ageInstall)
}

func knownHosts(_ *profile.Profile) string {
	return lines(
		"|1|"+base64ish("kh1", 27)+"=|"+base64ish("kh2", 27)+"= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI"+base64ish("gh", 43),
		"|1|"+base64ish("kh3", 27)+"=|"+base64ish("kh4", 27)+"= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI"+base64ish("staging", 43),
	)
}

const rootHistory = `apt update && apt upgrade -y
systemctl status nginx
journalctl -u bakery -n 100 --no-pager
vim /etc/nginx/sites-available/bakery
nginx -t && systemctl reload nginx
certbot --nginx -d shop.hazelbakery.example
systemctl status certbot.timer
tail -f /var/log/nginx/access.log
fail2ban-client status sshd
ufw status verbose
vim /etc/fail2ban/jail.local
systemctl restart fail2ban
su - postgres
psql -U bakery -h 127.0.0.1 bakery
vim /root/scripts/backup.sh
chmod 700 /root/scripts/backup.sh
/root/scripts/backup.sh
ls -la /var/backups/bakery/
crontab -e
cat /etc/cron.d/bakery-backup
df -h
du -sh /var/log/*
journalctl --vacuum-size=200M
apt autoremove -y
systemctl restart bakery
curl -sI https://shop.hazelbakery.example | head -5
htop
last -n 20
who
exit
`

const deployHistory = `cd /srv/bakery
git pull
npm ci --omit=dev
npm run build
sudo systemctl restart bakery
sudo systemctl status bakery
curl -s localhost:3000/healthz
tail -n 50 /var/log/bakery/app.log
node -v
cat .env
exit
`

const martinHistory = `sudo -i
ls
cd /srv/bakery
git log --oneline | head
sudo tail -f /var/log/nginx/error.log
sudo systemctl restart bakery
sudo journalctl -u bakery -f
htop
sudo du -sh /var/lib/postgresql
sudo -u postgres psql -c '\l'
vim ~/notes/todo.txt
sudo apt update
sudo apt list --upgradable
exit
`

var _ = path.Join
