package profile

import "time"

// Default is a small Ubuntu 22.04 VPS: the most common thing on the
// internet, so nothing about it stands out.
func Default() *Profile {
	return &Profile{
		Hostname:      "srv-web01",
		Domain:        "",
		OSName:        "Ubuntu",
		OSVersion:     "22.04.4 LTS",
		OSCodename:    "jammy",
		OSPretty:      "Ubuntu 22.04.4 LTS",
		Kernel:        "5.15.0-113-generic",
		KernelVersion: "#123-Ubuntu SMP Fri May 24 09:35:29 UTC 2024",
		Arch:          "x86_64",
		CPUModel:      "Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz",
		CPUCores:      2,
		MemMB:         3936,
		SwapMB:        0,
		DiskGB:        40,
		DiskUsedPct:   31,
		Interface:     "eth0",
		IPv4:          "10.20.30.41",
		Netmask:       "255.255.255.0",
		Gateway:       "10.20.30.1",
		MAC:           "52:54:00:6b:3c:58",
		Timezone:      "Etc/UTC",
		BootedAgo:     37*24*time.Hour + 5*time.Hour + 12*time.Minute,
		Role:          "small Ubuntu 22.04 VPS running nginx as a reverse proxy in front of a Node.js app (a bakery's online shop) with a PostgreSQL database; managed by one sysadmin who logs in occasionally",
		Users: []User{
			{Name: "root", UID: 0, GID: 0, Gecos: "root", Home: "/root", Shell: "/bin/bash"},
			{Name: "daemon", UID: 1, GID: 1, Gecos: "daemon", Home: "/usr/sbin", Shell: "/usr/sbin/nologin"},
			{Name: "bin", UID: 2, GID: 2, Gecos: "bin", Home: "/bin", Shell: "/usr/sbin/nologin"},
			{Name: "sys", UID: 3, GID: 3, Gecos: "sys", Home: "/dev", Shell: "/usr/sbin/nologin"},
			{Name: "sync", UID: 4, GID: 65534, Gecos: "sync", Home: "/bin", Shell: "/bin/sync"},
			{Name: "games", UID: 5, GID: 60, Gecos: "games", Home: "/usr/games", Shell: "/usr/sbin/nologin"},
			{Name: "man", UID: 6, GID: 12, Gecos: "man", Home: "/var/cache/man", Shell: "/usr/sbin/nologin"},
			{Name: "lp", UID: 7, GID: 7, Gecos: "lp", Home: "/var/spool/lpd", Shell: "/usr/sbin/nologin"},
			{Name: "mail", UID: 8, GID: 8, Gecos: "mail", Home: "/var/mail", Shell: "/usr/sbin/nologin"},
			{Name: "news", UID: 9, GID: 9, Gecos: "news", Home: "/var/spool/news", Shell: "/usr/sbin/nologin"},
			{Name: "uucp", UID: 10, GID: 10, Gecos: "uucp", Home: "/var/spool/uucp", Shell: "/usr/sbin/nologin"},
			{Name: "proxy", UID: 13, GID: 13, Gecos: "proxy", Home: "/bin", Shell: "/usr/sbin/nologin"},
			{Name: "www-data", UID: 33, GID: 33, Gecos: "www-data", Home: "/var/www", Shell: "/usr/sbin/nologin"},
			{Name: "backup", UID: 34, GID: 34, Gecos: "backup", Home: "/var/backups", Shell: "/usr/sbin/nologin"},
			{Name: "list", UID: 38, GID: 38, Gecos: "Mailing List Manager", Home: "/var/list", Shell: "/usr/sbin/nologin"},
			{Name: "irc", UID: 39, GID: 39, Gecos: "ircd", Home: "/run/ircd", Shell: "/usr/sbin/nologin"},
			{Name: "nobody", UID: 65534, GID: 65534, Gecos: "nobody", Home: "/nonexistent", Shell: "/usr/sbin/nologin"},
			{Name: "systemd-network", UID: 100, GID: 102, Gecos: "systemd Network Management,,,", Home: "/run/systemd", Shell: "/usr/sbin/nologin"},
			{Name: "systemd-resolve", UID: 101, GID: 103, Gecos: "systemd Resolver,,,", Home: "/run/systemd", Shell: "/usr/sbin/nologin"},
			{Name: "messagebus", UID: 102, GID: 105, Gecos: "", Home: "/nonexistent", Shell: "/usr/sbin/nologin"},
			{Name: "sshd", UID: 104, GID: 65534, Gecos: "", Home: "/run/sshd", Shell: "/usr/sbin/nologin"},
			{Name: "postgres", UID: 110, GID: 116, Gecos: "PostgreSQL administrator,,,", Home: "/var/lib/postgresql", Shell: "/bin/bash"},
			{Name: "deploy", UID: 1000, GID: 1000, Gecos: "Deploy,,,", Home: "/home/deploy", Shell: "/bin/bash"},
			{Name: "martin", UID: 1001, GID: 1001, Gecos: "Martin Kowalski,,,", Home: "/home/martin", Shell: "/bin/bash"},
		},
		Processes: []Process{
			{PID: 1, User: "root", CPU: 0.0, Mem: 0.2, VSZ: 167584, RSS: 11912, TTY: "?", Stat: "Ss", Start: "Aug11", Time: "0:41", Command: "/sbin/init"},
			{PID: 2, User: "root", CPU: 0.0, Mem: 0.0, VSZ: 0, RSS: 0, TTY: "?", Stat: "S", Start: "Aug11", Time: "0:00", Command: "[kthreadd]"},
			{PID: 3, User: "root", CPU: 0.0, Mem: 0.0, VSZ: 0, RSS: 0, TTY: "?", Stat: "I<", Start: "Aug11", Time: "0:00", Command: "[rcu_gp]"},
			{PID: 4, User: "root", CPU: 0.0, Mem: 0.0, VSZ: 0, RSS: 0, TTY: "?", Stat: "I<", Start: "Aug11", Time: "0:00", Command: "[rcu_par_gp]"},
			{PID: 11, User: "root", CPU: 0.0, Mem: 0.0, VSZ: 0, RSS: 0, TTY: "?", Stat: "S", Start: "Aug11", Time: "0:03", Command: "[ksoftirqd/0]"},
			{PID: 12, User: "root", CPU: 0.0, Mem: 0.0, VSZ: 0, RSS: 0, TTY: "?", Stat: "I", Start: "Aug11", Time: "2:17", Command: "[rcu_sched]"},
			{PID: 13, User: "root", CPU: 0.0, Mem: 0.0, VSZ: 0, RSS: 0, TTY: "?", Stat: "S", Start: "Aug11", Time: "0:01", Command: "[migration/0]"},
			{PID: 118, User: "root", CPU: 0.0, Mem: 0.0, VSZ: 0, RSS: 0, TTY: "?", Stat: "S", Start: "Aug11", Time: "0:19", Command: "[kswapd0]"},
			{PID: 231, User: "root", CPU: 0.0, Mem: 0.0, VSZ: 0, RSS: 0, TTY: "?", Stat: "I<", Start: "Aug11", Time: "0:00", Command: "[kworker/0:1H-kblockd]"},
			{PID: 342, User: "root", CPU: 0.0, Mem: 0.8, VSZ: 51472, RSS: 32744, TTY: "?", Stat: "S<s", Start: "Aug11", Time: "0:22", Command: "/lib/systemd/systemd-journald"},
			{PID: 381, User: "root", CPU: 0.0, Mem: 0.1, VSZ: 26016, RSS: 6488, TTY: "?", Stat: "Ss", Start: "Aug11", Time: "0:03", Command: "/lib/systemd/systemd-udevd"},
			{PID: 542, User: "systemd-network", CPU: 0.0, Mem: 0.1, VSZ: 16116, RSS: 7220, TTY: "?", Stat: "Ss", Start: "Aug11", Time: "0:06", Command: "/lib/systemd/systemd-networkd"},
			{PID: 544, User: "systemd-resolve", CPU: 0.0, Mem: 0.3, VSZ: 25528, RSS: 13160, TTY: "?", Stat: "Ss", Start: "Aug11", Time: "0:31", Command: "/lib/systemd/systemd-resolved"},
			{PID: 601, User: "root", CPU: 0.0, Mem: 0.0, VSZ: 6820, RSS: 2900, TTY: "?", Stat: "Ss", Start: "Aug11", Time: "0:00", Command: "/usr/sbin/cron -f -P"},
			{PID: 603, User: "messagebus", CPU: 0.0, Mem: 0.1, VSZ: 8664, RSS: 4460, TTY: "?", Stat: "Ss", Start: "Aug11", Time: "0:04", Command: "@dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only"},
			{PID: 612, User: "root", CPU: 0.0, Mem: 0.4, VSZ: 30124, RSS: 18644, TTY: "?", Stat: "Ss", Start: "Aug11", Time: "0:00", Command: "/usr/bin/python3 /usr/bin/networkd-dispatcher --run-startup-triggers"},
			{PID: 614, User: "root", CPU: 0.0, Mem: 0.1, VSZ: 15332, RSS: 7444, TTY: "?", Stat: "Ss", Start: "Aug11", Time: "0:00", Command: "/lib/systemd/systemd-logind"},
			{PID: 619, User: "syslog", CPU: 0.0, Mem: 0.1, VSZ: 222400, RSS: 5820, TTY: "?", Stat: "Ssl", Start: "Aug11", Time: "0:25", Command: "/usr/sbin/rsyslogd -n -iNONE"},
			{PID: 651, User: "root", CPU: 0.0, Mem: 0.0, VSZ: 6176, RSS: 1092, TTY: "tty1", Stat: "Ss+", Start: "Aug11", Time: "0:00", Command: "/sbin/agetty -o -p -- \\u --noclear tty1 linux"},
			{PID: 672, User: "root", CPU: 0.0, Mem: 0.2, VSZ: 15436, RSS: 9128, TTY: "?", Stat: "Ss", Start: "Aug11", Time: "0:00", Command: "sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 startups"},
			{PID: 733, User: "root", CPU: 0.0, Mem: 0.0, VSZ: 10232, RSS: 3164, TTY: "?", Stat: "Ss", Start: "Aug11", Time: "0:00", Command: "nginx: master process /usr/sbin/nginx -g daemon on; master_process on;"},
			{PID: 734, User: "www-data", CPU: 0.0, Mem: 0.1, VSZ: 10884, RSS: 5116, TTY: "?", Stat: "S", Start: "Aug11", Time: "1:13", Command: "nginx: worker process"},
			{PID: 735, User: "www-data", CPU: 0.0, Mem: 0.1, VSZ: 10884, RSS: 5180, TTY: "?", Stat: "S", Start: "Aug11", Time: "1:09", Command: "nginx: worker process"},
			{PID: 801, User: "postgres", CPU: 0.0, Mem: 0.7, VSZ: 219896, RSS: 29604, TTY: "?", Stat: "Ss", Start: "Aug11", Time: "0:12", Command: "/usr/lib/postgresql/14/bin/postgres -D /var/lib/postgresql/14/main -c config_file=/etc/postgresql/14/main/postgresql.conf"},
			{PID: 803, User: "postgres", CPU: 0.0, Mem: 0.1, VSZ: 219896, RSS: 5820, TTY: "?", Stat: "Ss", Start: "Aug11", Time: "0:00", Command: "postgres: 14/main: checkpointer"},
			{PID: 804, User: "postgres", CPU: 0.0, Mem: 0.1, VSZ: 219896, RSS: 5976, TTY: "?", Stat: "Ss", Start: "Aug11", Time: "0:04", Command: "postgres: 14/main: background writer"},
			{PID: 805, User: "postgres", CPU: 0.0, Mem: 0.2, VSZ: 219896, RSS: 9184, TTY: "?", Stat: "Ss", Start: "Aug11", Time: "0:03", Command: "postgres: 14/main: walwriter"},
			{PID: 806, User: "postgres", CPU: 0.0, Mem: 0.1, VSZ: 220464, RSS: 7364, TTY: "?", Stat: "Ss", Start: "Aug11", Time: "0:09", Command: "postgres: 14/main: autovacuum launcher"},
			{PID: 807, User: "postgres", CPU: 0.0, Mem: 0.1, VSZ: 74300, RSS: 5052, TTY: "?", Stat: "Ss", Start: "Aug11", Time: "0:27", Command: "postgres: 14/main: stats collector"},
			{PID: 808, User: "postgres", CPU: 0.0, Mem: 0.1, VSZ: 220224, RSS: 6428, TTY: "?", Stat: "Ss", Start: "Aug11", Time: "0:00", Command: "postgres: 14/main: logical replication launcher"},
			{PID: 912, User: "deploy", CPU: 0.3, Mem: 2.1, VSZ: 1016588, RSS: 84960, TTY: "?", Stat: "Ssl", Start: "Aug11", Time: "38:12", Command: "node /srv/bakery/dist/server.js"},
			{PID: 1204, User: "root", CPU: 0.0, Mem: 0.1, VSZ: 1234568, RSS: 5088, TTY: "?", Stat: "Ssl", Start: "Aug11", Time: "0:00", Command: "/usr/bin/containerd"},
			{PID: 1580, User: "root", CPU: 0.0, Mem: 0.3, VSZ: 234544, RSS: 13500, TTY: "?", Stat: "Ssl", Start: "Aug11", Time: "0:54", Command: "/usr/lib/snapd/snapd"},
			{PID: 1591, User: "root", CPU: 0.0, Mem: 0.1, VSZ: 8312, RSS: 3976, TTY: "?", Stat: "Ss", Start: "Aug11", Time: "0:00", Command: "/usr/sbin/atd -f"},
			{PID: 2211, User: "root", CPU: 0.0, Mem: 0.4, VSZ: 249144, RSS: 17284, TTY: "?", Stat: "Ssl", Start: "Aug11", Time: "1:01", Command: "/usr/bin/python3 /usr/share/unattended-upgrades/unattended-upgrade-shutdown --wait-for-signal"},
		},
		Packages: []string{
			"nginx", "nodejs", "npm", "postgresql-14", "certbot", "python3-certbot-nginx",
			"git", "curl", "wget", "vim", "htop", "ufw", "fail2ban", "rsync", "unzip",
			"openssh-server", "cron", "logrotate", "snapd", "containerd",
		},
	}
}
